### ISSUE TITLE
[BUG] 동일한 제목으로 글 등록 시 500에러 발생

### ISSUE THREAD

**Issue by ars-ki-00** [wafflestudio19-5/team7-server#116]
## 기대한 동작
동일한 제목으로 여러 개의 글 등록 가능

## 현재 동작
동일한 제목으로 글 등록 시 500에러 발생

## 재현 방법
글 등록 후, 동일한 제목으로 재등록 시도.

## 기타
![image](https://user-images.githubusercontent.com/48665265/148632762-10aa8c34-78a4-4e57-8ba8-06b6760878fa.png)

**Comment by HyungGeun-Cho** [comment]
프론트 쪽에서도 세부 에러 처리가 더 필요할 것 같습니다!

**Comment by wallabyg** [comment]
500 에러는 서버 쪽에서 처리해야되는 에러라 저희가 먼저 처리하고, 400대 에러를 전달드리는 방향으로 갈 거 같습니다.
