### ISSUE TITLE
회원가입 시 졸업생 선택시 넘어가지 않는 버그

### ISSUE THREAD

**Issue by IHIHHIHI** [wafflestudio19-5/team7-server#117]
## 기대한 동작
회원가입에서 모든 정보를 채워넣고 다음 버튼을 누르면 넘어가야 함.

## 현재 동작
다음 버튼을 눌러도 넘어가지 않음.
<img width="576" alt="스크린샷 2022-01-08 오후 2 39 33" src="https://user-images.githubusercontent.com/52493099/148633030-bf2d0dda-79ba-4edf-8ecb-e2e6827616d7.png">

## 재현 방법
1. 회원가입에서 졸업생 선택
2. 모든 정보를 채워넣음
3. 다음 버튼을 눌러도 넘어가지 않음

**Comment by wallabyg** [comment]
@IHIHHIHI 레포지토리 잘못 선택하신 것 같습니다!
저희 서비스는 velog입니다 :)

**Comment by IHIHHIHI** [comment]
> @IHIHHIHI 레포지토리 잘못 선택하신 것 같습니다! 저희 서비스는 velog입니다 :)

죄송합니다...!
