### ISSUE TITLE
예외 처리 로직

### ISSUE THREAD

**Issue by wallabyg** [wafflestudio19-5/team7-server#30]
## 해결해야 하는 문제
예외가 발생했을 경우 에러 코드 등을 담은 적절한 response를 반환해야 합니다.

## 기능 설명
HTTP 상태 코드 400대의 에러가 발생하면 에러 코드와 메시지를 담은 response를 반환합니다.

## 구현 방법
```@RestControllerAdvice```를 사용하여 예외 처리를 담당하는 ControllerAdvice 클래스를 생성합니다.

## 대안
도메인별로 다른 ControllerAdvice를 생성하거나, 모든 도메인이 하나의 ControllerAdvice를 사용할 수 있습니다.

**Comment by nemga123** [comment]
예외처리 제가 이번 pr #32 하면서 필요하여 대충 스켈레톤으로 구현한 것이 있는데 확인하고 중복되는 것은 안해주셔도 될 것 같습니다.

**Comment by wallabyg** [comment]
현수님이 #32 에서 처리해주셔서 이슈 닫아도 될 것 같습니다!
